---
title: "Trust and Partisan Segregation"
author: "Noah Daponte-Smith"
date: "4/22/2022"
output: pdf_document
---

```{r setup, include=FALSE, warning = FALSE}
library(tidyverse)
library(estimatr)
library(knitr)
library(modelsummary)
setwd("C:/Users/dapon/Dropbox/Harvard/trust/data")
full <- read_csv("survey_clean/2021-recontact-with-seg-variables.csv")

```

## General trust and trust in neighbors, by 2020 vote


```{r 2020vote, echo = FALSE, warning = FALSE, message = FALSE}
# get only trump and biden voters
df_twoparty <- full %>% 
    filter(pres_vote_2020 %in% c("Donald Trump","Joe Biden")) %>% 
    mutate(vote_biden = ifelse(pres_vote_2020 == "Joe Biden", 1, 0))
  
  # democratic exposure, general trust, pres vote choice 
mod_general_dem_pres_county <- lm_robust(data = df_twoparty, 
                                          denisen_general ~ w.mean.d.post*vote_biden + 
                                            gender + edlevel + white_non_hispanic + age + income_ordinal + 
                                          non_white_prop + poverty_rate + median_income,
                                          fixed_effects = vb.vf_county_code,
                                         clusters = vb.vf_county_code)
  # democratic exposure, neighbors trust, pres vote choice 
mod_neighbors_dem_pres_county <- lm_robust(
    data = df_twoparty, denisen_neighbor ~ 
      w.mean.d.post*vote_biden + 
      gender + edlevel + white_non_hispanic + age + income_ordinal + 
      non_white_prop + poverty_rate + median_income, 
    fixed_effects = vb.vf_county_code,
    clusters = vb.vf_county_code)

  # democratic exposure, general trust, pres vote choice 
mod_general_rep_pres_county <- lm_robust(data = df_twoparty, 
                                          denisen_general ~ w.mean.r.post*vote_biden + 
                                            gender + edlevel + white_non_hispanic + age + income_ordinal + 
                                          non_white_prop + poverty_rate + median_income,
                                          fixed_effects = vb.vf_county_code,
                                         clusters = vb.vf_county_code)
  # democratic exposure, neighbors trust, pres vote choice 
mod_neighbors_rep_pres_county <- lm_robust(
    data = df_twoparty, denisen_neighbor ~ 
      w.mean.r.post*vote_biden + 
      gender + edlevel + white_non_hispanic + age + income_ordinal + 
      non_white_prop + poverty_rate + median_income, 
    fixed_effects = vb.vf_county_code,
    clusters = vb.vf_county_code)


# report the pres-vote results 
modelsummary(
    list("General trust, Dem exposure" = mod_general_dem_pres_county, 
         "Neighbors trust, Dem exposure" = mod_neighbors_dem_pres_county,
         "General trust, Rep exposure" = mod_general_rep_pres_county,
         "Neighbors trust, Rep exposure" = mod_neighbors_rep_pres_county),
    output = "markdown",
    stars = TRUE,
    coef_map = c(
      "w.mean.d.post" = "Dem exposure (weighted)", 
      "vote_biden" = "Voted Biden",
      "w.mean.d.post:vote_biden" = "Dem exposure * Voted Biden",
      "w.mean.r.post" = "Rep exposure (weighted)",
      "w.mean.r.post:vote_biden" = "Rep exposure * Voted Biden",
      "genderMale" = "Gender Male",
      "genderOther/Prefer not to answer" = "Gender Other",
      "edlevel" = "Education (ordinal)",
      "white_non_hispanic" = "White (non-Hispanic)",
      "age" = "Age",
      "income_ordinal" = "Income (ordinal)",
      "non_white_prop" = "Pct. non-white (blockgroup)",
      "poverty_rate" = "Poverty rate (blockgroup)",
      "median_income" = "Median income (blockgroup)"
      
    ),
    add_rows = bind_rows(bind_cols("County fixed effects","Yes","Yes", "Yes","Yes"),
                      bind_cols("Std. Error Clusters","County","County","County","County")),
    title = "General/neighbors trust, by presidential vote and partisan exposure",
  )

```

\newpage

## General trust and trust in neighbors, by  party-id (among Dem and Rep partisans)
```{r two_party_id, echo = FALSE, warning = FALSE, message = FALSE}
# democratic exposure, general trust, two-party id 
mod_general_dem_partyid_county <- lm_robust(
  data = full, 
  denisen_general ~ w.mean.d.post*democrat_id_twoparty + 
    gender + edlevel + white_non_hispanic + age + income_ordinal + 
    non_white_prop + poverty_rate + median_income, 
  fixed_effects = vb.vf_county_code, 
  clusters = vb.vf_county_code
)
# democratic exposure, neighbors trust, two-party id 
mod_neighbors_dem_partyid_county <- lm_robust(
  data = full, 
  denisen_neighbor ~ w.mean.d.post*democrat_id_twoparty + 
    gender + edlevel + white_non_hispanic + age + income_ordinal + 
    non_white_prop + poverty_rate + median_income, 
  fixed_effects = vb.vf_county_code, 
  clusters = vb.vf_county_code
)

# democratic exposure, general trust, two-party id 
mod_general_rep_partyid_county <- lm_robust(
  data = full, 
  denisen_general ~ w.mean.r.post*democrat_id_twoparty + 
    gender + edlevel + white_non_hispanic + age + income_ordinal + 
    non_white_prop + poverty_rate + median_income, 
  fixed_effects = vb.vf_county_code, 
  clusters = vb.vf_county_code
)
# democratic exposure, neighbors trust, two-party id 
mod_neighbors_rep_partyid_county <- lm_robust(
  data = full, 
  denisen_neighbor ~ w.mean.r.post*democrat_id_twoparty + 
    gender + edlevel + white_non_hispanic + age + income_ordinal + 
    non_white_prop + poverty_rate + median_income, 
  fixed_effects = vb.vf_county_code, 
  clusters = vb.vf_county_code
)

modelsummary(
  list("General trust, Dem exposure" = mod_general_dem_partyid_county, 
       "Neighbors trust, Dem exposure" = mod_neighbors_dem_partyid_county,
       "General trust, Rep exposure" = mod_general_rep_partyid_county,
       "Neighbors trust, Rep exposure" = mod_neighbors_rep_partyid_county), 
  stars = TRUE,
  output = "markdown",
  coef_map = c("w.mean.d.post" = "Dem exposure (weighted)",
               "democrat_id_twoparty" = "Party ID = Dem", 
               "w.mean.d.post:democrat_id_twoparty" = "Dem exposure * Party ID = Dem", 
               "w.mean.r.post" = "Rep exposure (weighted)",
               "w.mean.r.post:democrat_id_twoparty" = "Rep exposure * Party ID = Dem",
               "genderMale" = "Gender Male",
               "genderOther/Prefer not to answer" = "Gender Other",
               "edlevel" = "Education (ordinal)",
               "white_non_hispanic" = "White (non-Hispanic)",
               "age" = "Age",
               "income_ordinal" = "Income (ordinal)",
               "non_white_prop" = "Pct. non-white (blockgroup)",
               "poverty_rate" = "Poverty rate (blockgroup)",
               "median_income" = "Median income (blockgroup)"),
  add_rows = bind_rows(bind_cols("County fixed effects","Yes","Yes", "Yes","Yes"),
                       bind_cols("Std. Error Clusters","County","County","County","County")),
  title = "General/neighbors trust, by two-party ID and partisan exposure",
)


full_cor <- full %>% 
  select(denisen_general, denisen_neighbor, pres_vote_2020,
         w.mean.d.post, w.mean.r.post) %>% 
  na.omit() 



general_demexp_cor <- cor(full_cor$denisen_general, full_cor$w.mean.d.post)
neighbor_demexp_cor <- cor(full_cor$denisen_neighbor, full_cor$w.mean.d.post)
general_repexp_cor <- cor(full_cor$denisen_general, full_cor$w.mean.r.post)
neighbor_repexp_cor <- cor(full_cor$denisen_neighbor, full_cor$w.mean.r.post)


general_demexp_cor_dem <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Joe Biden"],
                                full_cor$w.mean.d.post[full_cor$pres_vote_2020 == "Joe Biden"])
neighbor_demexp_cor_dem <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Joe Biden"],
                                full_cor$w.mean.d.post[full_cor$pres_vote_2020 == "Joe Biden"])
general_repexp_cor_dem <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Joe Biden"],
                                full_cor$w.mean.r.post[full_cor$pres_vote_2020 == "Joe Biden"])
neighbor_repexp_cor_dem <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Joe Biden"],
                                full_cor$w.mean.r.post[full_cor$pres_vote_2020 == "Joe Biden"])

general_demexp_cor_rep <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Donald Trump"],
                                full_cor$w.mean.d.post[full_cor$pres_vote_2020 == "Donald Trump"])
neighbor_demexp_cor_rep <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Donald Trump"],
                                full_cor$w.mean.d.post[full_cor$pres_vote_2020 == "Donald Trump"])
general_repexp_cor_rep <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Donald Trump"],
                                full_cor$w.mean.r.post[full_cor$pres_vote_2020 == "Donald Trump"])
neighbor_repexp_cor_rep <- cor(full_cor$denisen_general[full_cor$pres_vote_2020 == "Donald Trump"],
                                full_cor$w.mean.r.post[full_cor$pres_vote_2020 == "Donald Trump"])


cbind(c("General trust vs. Dem exposure",
        "Neighbor trust vs. Dem exposure",
        "General trust vs. Rep exposure",
        "Neighbor trust vs. Rep exposure",
        "General trust vs. Dem exposure",
        "Neighbor trust vs. Dem exposure",
        "General trust vs. Rep exposure",
        "Neighbor trust vs. Rep exposure",
        "General trust vs. Dem exposure",
        "Neighbor trust vs. Dem exposure",
        "General trust vs. Rep exposure",
        "Neighbor trust vs. Rep exposure"),
      c("Full","Full","Full","Full",
        "Dem","Dem","Dem","Dem",
        "Rep","Rep","Rep","Rep"),
  c(round(general_demexp_cor, 3), 
    round(neighbor_demexp_cor, 3),
    round(general_repexp_cor, 3), 
    round(neighbor_repexp_cor, 3),
    round(general_demexp_cor_dem, 3),
    round(neighbor_demexp_cor_dem, 3),
    round(general_repexp_cor_dem, 3),
    round(neighbor_repexp_cor_dem, 3),
    round(general_demexp_cor_rep, 3),
    round(neighbor_demexp_cor_rep, 3 ),
    round(general_repexp_cor_rep, 3),
    round(neighbor_repexp_cor_rep, 3)
    )) %>% 
  as_tibble() %>% 
  rename(Relationship = V1, 
         Group = V2, 
         Coefficient = V3) %>% 
  kable()
      
```

\newpage
## General trust and trust in neighbors, by party ID (Rep, Dem, Ind)
```{r three_party_id, echo = FALSE, warning = FALSE, message = FALSE}

# democratic exposure, general trust, party id (with independents)
mod_general_dem_threepartyid_county <- lm_robust(
  data = full %>% filter(party_3 %in% c("Democrat","Republican","Independent")) %>% 
    mutate(party_3_factor = factor(party_3, levels = c("Republican","Democrat","Independent"))), 
  denisen_general ~ w.mean.d.post*party_3_factor + 
    gender + edlevel + white_non_hispanic + age + income_ordinal + 
    non_white_prop + poverty_rate + median_income, 
  fixed_effects = vb.vf_county_code, 
  clusters = vb.vf_county_code
)
# democratic exposure, neighbors trust, party id (with independents)
mod_neighbors_dem_threepartyid_county <- lm_robust( 
  data = full %>% filter(party_3 %in% c("Democrat","Republican","Independent")) %>% 
    mutate(party_3_factor = factor(party_3, levels = c("Republican","Democrat","Independent"))),
  denisen_neighbor ~ w.mean.d.post*party_3_factor + 
    gender + edlevel + white_non_hispanic + age + income_ordinal + 
    non_white_prop + poverty_rate + median_income, 
  fixed_effects = vb.vf_county_code, 
  clusters = vb.vf_county_code
)
  
# report the party id  results 
modelsummary(
  list("General trust" = mod_general_dem_threepartyid_county, 
       "Neighbors trust" = mod_neighbors_dem_threepartyid_county),
  stars = TRUE,
  output = "markdown",
  coef_map = c("w.mean.d.post" = "Democratic exposure (weighted)",
               "party_3_factorIndependent" = "Party ID = Independent",
               "party_3_factorDemocrat" = "Party ID = Democrat",
               "w.mean.d.post:party_3_factorDemocrat" = "Dem exposure * Party ID = Dem",
               "w.mean.d.post:party_3_factorIndependent" = "Dem exposure * Party ID = Ind",
               "genderMale" = "Gender Male",
               "genderOther/Prefer not to answer" = "Gender Other",
               "edlevel" = "Education (ordinal)",
               "white_non_hispanic" = "White (non-Hispanic)",
               "age" = "Age",
               "income_ordinal" = "Income (ordinal)",
               "non_white_prop" = "Pct. non-white (blockgroup)",
               "poverty_rate" = "Poverty rate (blockgroup)",
               "median_income" = "Median income (blockgroup)"),
  add_rows = bind_rows(bind_cols("County fixed effects","Yes","Yes"),
                       bind_cols("Std. Error Clusters","County","County")),
  title = "General/neighbors trust, by three-party ID and partisan exposure",
)

```